config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'pages#home'
  
  resources :users, :only => [:new, :create]
  resources :firearms
  resources :ammos
  resources :manufacturers, :only => [:index, :show]

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#delete'

end

app/models/ammo.rb
class Ammo < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :manufacturer, :optional => true
    has_and_belongs_to_many :firearms
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/firearm.rb
class Firearm < ApplicationRecord
    belongs_to :user, :optional => true
    belongs_to :manufacturer, :optional => true
    has_and_belongs_to_many :ammos
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
    has_many :firearms
    has_many :ammos
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :email, :uniqueness => true, :presence => true
    has_many :firearms
    has_many :ammos
end

app/controllers/ammos_controller.rb
class AmmosController < ApplicationController
  before_action :check_if_owner, :only => [:show, :edit]

  require 'net/http'
  require 'uri'
  require 'json'

  def index
    @ammos = Ammo.where(:user_id => @current_user.id)
  end

  def new
    @ammo = Ammo.new
  end

  def create
    ammo = Ammo.create ammo_params
    ammo.update(:user_id => @current_user.id)

    # Auto associate firearms that share the same calibre string 
    @current_user.firearms.where(calibre: ammo.calibre).each do |firearm|
      ammo.firearms << firearm
    end
    
    redirect_to ammo
  end

  def edit
    @ammo = Ammo.find params[:id]
  end

  def update
    ammo = Ammo.find params[:id]
    ammo.update ammo_params

    # Auto associate firearms that share the same calibre string 
    ammo.firearms.destroy_all
    @current_user.firearms.where(calibre: ammo.calibre).each do |firearm|
      ammo.firearms << firearm
    end

    redirect_to ammo
  end

  def show
    @ammo = Ammo.find params[:id]

    uri = URI.parse("https://api.tarkov.dev/graphql")

    header = { "Content-Type": "application/json" }
    query = { "query": "{ ammo { item { name } ricochetChance } }" }
    
    # Create the HTTP object
    http = Net::HTTP.new(uri.host, uri.port)
    http.use_ssl = true
    request = Net::HTTP::Post.new(uri.request_uri, header)
    request.body = query.to_json

    # Send the request
    response = http.request(request)

    # Convert to JSON and loop through data
    response_data = JSON.parse(response.body)
    response_data["data"]["ammo"].each do |ammo|
      # Check if the item name matches
      if ammo["item"]["name"] == "#{ @ammo.calibre } #{ @ammo.name }"
        # Print the ricochetChance associated with this item
        puts "The ricochetChance of #{ @ammo.name } is #{ ammo["ricochetChance"] }"
      end
    end

    # Display request results
    # puts response.code
    # puts response.message
    puts response.body

  end

  def destroy
    ammo = Ammo.find params[:id]
    ammo.destroy
    redirect_to ammos_path
  end

  private

  def ammo_params
    params.require(:ammo).permit(:name, :calibre, :manufacturer_id, :bullet_velocity, :fragmentation_chance, :ricochet_chance, :quantity, :image)
  end

  def check_if_owner
    ammo = Ammo.find_by :id => params[:id]
    redirect_to root_path unless @current_user.id == ammo.user_id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :fetch_user

    private
    
    def fetch_user
        @current_user = User.find_by :id => session[:user_id]
        session[:user_id] = nil unless @current_user.present?
    end
end

app/controllers/firearms_controller.rb
class FirearmsController < ApplicationController
    before_action :check_if_owner, :only => [:show, :edit]

    def index
        @firearms = Firearm.where(:user_id => @current_user.id)
    end
  
    def new
        @firearm = Firearm.new
    end
  
    def create
        firearm = Firearm.create firearm_params
        firearm.update(:user_id => @current_user.id)

        # Auto associate ammos that share the same calibre string 
        @current_user.ammos.where(:calibre => firearm.calibre).each do |ammo|
            firearm.ammos << ammo
        end

        if params[:file].present?
            req = Cloudinary::Uploader.upload(params[:file])
            firearm.image = req["public_id"]
            firearm.save
        end

        redirect_to firearm
    end
  
    def edit
        @firearm = Firearm.find params[:id]
    end
  
    def update
        firearm = Firearm.find params[:id]

        if params[:file].present?
            req = Cloudinary::Uploader.upload(params[:file])
            firearm.image = req["public_id"]
            firearm.save
        end

        firearm.update firearm_params

        # Auto associate ammos that share the same calibre string 
        firearm.ammos.destroy_all
        @current_user.ammos.where(:calibre => firearm.calibre).each do |ammo|
            firearm.ammos << ammo
        end

        redirect_to firearm
    end
  
    def show
        @firearm = Firearm.find params[:id]
    end
  
    def destroy
        firearm = Firearm.find params[:id]
        firearm.destroy
        redirect_to firearms_path
    end

    private

    def firearm_params
        params.require(:firearm).permit(:model, :calibre, :manufacturer_id, :family, :fire_rate, :effective_distance, :quantity, :image)
    end

    def check_if_owner
        firearm = Firearm.find_by :id => params[:id]
        redirect_to root_path unless @current_user.id == firearm.user_id
    end
end

app/controllers/manufacturers_controller.rb
class ManufacturersController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end

  def show
    @manufacturer = Manufacturer.find params[:id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
    user = User.find_by :email => params[:email]

    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to firearms_path
    else
      flash[:error] = "Invalid username or password"
      redirect_to login_path
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create user_params

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private
  
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/ammos_helper.rb
module AmmosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/firearms_helper.rb
module FirearmsHelper
end

app/helpers/manufacturers_helper.rb
module ManufacturersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/ammos/_form.html.erb
<%= form_for @ammo do |f| %>

    <%= f.label :name %>
    <%= f.text_field :name, :required => true %>

    <%= f.label :calibre %>
    <%= f.select :calibre, options_for_select(["7.62x51mm", "5.56x45mm", "9x19mm", "5.45x39mm"], selected: @ammo.calibre), :include_blank => true %>
    <p class="note">NOTE: Selecting a calibre will associate all compatible firearms upon creation</p>

    <%= f.label :manufacturer_id %>
    <%= f.select :manufacturer_id, Manufacturer.pluck(:name, :id), :include_blank => true %>

    <%= f.label :bullet_velocity %>
    <%= f.number_field :bullet_velocity %>
    
    <%= f.label :fragmentation_chance %>
    <%= f.number_field :fragmentation_chance %>

    <%= f.label :ricochet_chance %>
    <%= f.number_field :ricochet_chance %>

    <%= f.label :quantity %>
    <%= f.number_field :quantity %>

    <%= f.label :image %>
    <%= f.text_field :image %>

    <%= f.submit :class => 'btn btn-success' %>

<% end %>

app/views/ammos/edit.html.erb
<h1>Edit ammo</h1>

<%= render :partial => 'form' %>

app/views/ammos/index.html.erb
<h1>All ammo</h1>

<div class="controls">
    <%= link_to "New ammo", new_ammo_path %>
</div>

<% @ammos.each do |ammo| %>

    <div class="listing">
        <%= link_to ammo.name, ammo %>
        <ul>
            <li>Calibre: <%= ammo.calibre %></li>
            <li>Manufacturer: <%= link_to ammo.manufacturer.name, ammo.manufacturer if ammo.manufacturer.present? %></li>
            <li>Bullet Velocity: <%= ammo.bullet_velocity %> <%= "m/s" if ammo.bullet_velocity.present? %></li>
            <li>Fragmentation Chance: <%= ammo.fragmentation_chance %><%= "%" if ammo.fragmentation_chance.present? %></li>
            <li>Ricochet Chance: <%= ammo.ricochet_chance %><%= "%" if ammo.ricochet_chance.present? %></li>
            <li>Quantity: <%= ammo.quantity %></li>
        </ul>
    </div>
<% end %>

<% if @ammos.empty? %>
    <p>You currently have no ammo under your account. Add some and you will see them here.</p>
<% end %>

app/views/ammos/new.html.erb
<h1>New ammo</h1>

<%= render :partial => 'form' %>

app/views/ammos/show.html.erb
<h1><%= @ammo.name %></h1>

<div class="controls">
    <%= link_to "Edit ammo", edit_ammo_path(@ammo) %>
    <%= link_to "Delete ammo", @ammo, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
</div>

<div class="listing">
    <%= image_tag @ammo.image, :class => 'feature' if @ammo.image.present? %>
    
    <ul>
        <li>Calibre: <%= @ammo.calibre %></li>
        <li>Manufacturer: <%= link_to @ammo.manufacturer.name, @ammo.manufacturer if @ammo.manufacturer.present? %></li>
        <li>Bullet Velocity: <%= @ammo.bullet_velocity %> <%= "m/s" if @ammo.bullet_velocity.present? %></li>
        <li>Fragmentation Chance: <%= @ammo.fragmentation_chance %><%= "%" if @ammo.fragmentation_chance.present? %></li>
        <li>Ricochet Chance: <%= @ammo.ricochet_chance %><%= "%" if @ammo.ricochet_chance.present? %></li>
        <li>Quantity: <%= @ammo.quantity %></li>
        <li>Compatible firearms in database:
            <ul>
                <% @ammo.firearms.each do |firearm| %>
                    <li><%= link_to firearm.model, firearm %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</div>

app/views/firearms/_form.html.erb
<%= form_for(@firearm, :html => { :multipart => true }) do |f| %>

    <%= f.label :model %>
    <%= f.text_field :model, :required => true %>

    <%= f.label :calibre %>
    <%= f.select :calibre, options_for_select(["7.62x51mm", "5.56x45mm", "9x19mm", "5.45x39mm"], selected: @firearm.calibre), :include_blank => true %>
    <p class="note">NOTE: Selecting a calibre will associate all compatible ammo upon creation</p>

    <%= f.label :manufacturer_id %>
    <%= f.select :manufacturer_id, Manufacturer.pluck(:name, :id), :include_blank => true %>

    <%= f.label :family %>
    <%= f.text_field :family %>
    
    <%= f.label :fire_rate %>
    <%= f.number_field :fire_rate %>

    <%= f.label :effective_distance %>
    <%= f.number_field :effective_distance %>

    <%= f.label :quantity %>
    <%= f.number_field :quantity %>

    <%= f.label :image %>
    <%= f.cl_image_upload :image %>

    <%= f.submit :class => 'btn btn-success' %>

<% end %>

app/views/firearms/edit.html.erb
<h1>Edit firearm</h1>

<%= render :partial => 'form' %>

app/views/firearms/index.html.erb
<h1>All firearms</h1>

<div class="controls">
    <%= link_to "New firearm", new_firearm_path if @current_user.present? %>
</div>

<% @firearms.each do |firearm| %>
    <div class="listing">
        <%= link_to firearm.model, firearm %>
        <ul>
            <li>Calibre: <%= firearm.calibre %></li>
            <li>Manufacturer: <%= link_to firearm.manufacturer.name, firearm.manufacturer if firearm.manufacturer.present? %></li>
            <li>Family: <%= firearm.family %></li>
            <li>Fire Rate: <%= firearm.fire_rate %> <%= "RPM" if firearm.fire_rate.present? %></li>
            <li>Effective Distance: <%= firearm.effective_distance %> <%= "m" if firearm.effective_distance.present? %></li>
            <li>Quantity: <%= firearm.quantity %></li>
        </ul>
    </div>
<% end %>

<% if @firearms.empty? %>
    <p>You currently have no firearms under your account. Add some and you will see them here.</p>
<% end %>

app/views/firearms/new.html.erb
<h1>New firearm</h1>

<%= render :partial => 'form' %>

app/views/firearms/show.html.erb
<h1><%= @firearm.model %></h1>

<div class="controls">
    <%= link_to "Edit firearm", edit_firearm_path(@firearm) %>
    <%= link_to "Delete firearm", @firearm, :method => :delete, :data => { :confirm => 'Are you sure?' } %>
</div>

<div class="listing">
    <% if @firearm.image.present? && @firearm.image =~ /^[\w-]+$/ %>
      <%= cl_image_tag @firearm.image, :class => 'feature' %>
    <% elsif @firearm.image.present? %>
      <%= image_tag @firearm.image, :class => 'feature' %>
    <% end %>

    <ul>
        <li>Calibre: <%= @firearm.calibre %></li>
        <li>Manufacturer: <%= link_to @firearm.manufacturer.name, @firearm.manufacturer if @firearm.manufacturer.present? %></li>
        <li>Family: <%= @firearm.family %></li>
        <li>Fire rate: <%= @firearm.fire_rate %> <%= "RPM" if @firearm.fire_rate.present? %></li>
        <li>Effective distance: <%= @firearm.effective_distance %> <%= "m" if @firearm.effective_distance.present? %></li>
        <li>Quantity: <%= @firearm.quantity %></li>
        <li>Compatible ammo in database:
            <ul>
                <% @firearm.ammos.each do |ammo| %>
                    <li><%= link_to ammo.name, ammo %> x <%= ammo.quantity %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Armory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/water.css@2/out/dark.css">
    <%= cloudinary_js_config %>

  </head>

  <body>

    <div class="container">
      <% if @current_user.present? %>
        <%= link_to "Firearms", firearms_path %>
        <%= link_to "Ammo", ammos_path %>
        <%= link_to "Manufacturers", manufacturers_path %>
        <%= link_to "Log out #{ @current_user.email }", login_path, :method => :delete %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Sign in", login_path %>
      <% end %>

      <%= yield %>

    </div>

  </body>
</html>

app/views/manufacturers/index.html.erb
<h1>All manufacturers</h1>

<% @manufacturers.each do |manufacturer| %>
    
    <div class="listing">
        <%= link_to manufacturer.name, manufacturer %>
        <ul>
            <li>Founder: <%= manufacturer.founder %></li>
            <li>Founded: <%= manufacturer.founded %></li>
            <li>Country: <%= manufacturer.country %></li>
        </ul>
    </div>
<% end %>

app/views/manufacturers/show.html.erb
<h1><%= @manufacturer.name %></h1>

<div class="listing">
    <%= image_tag @manufacturer.image, :class => 'feature' if @manufacturer.image.present? %>
    
    <ul>
        <li>Founder: <%= @manufacturer.founder %></li>
        <li>Founded: <%= @manufacturer.founded %></li>
        <li>Country: <%= @manufacturer.country %></li>
        <li>Firearms in database: 
            <% firearms = @current_user.firearms.where(:manufacturer_id => @manufacturer.id) %>
            <ul>
                <% firearms.each do |firearm| %>
                    <li><%= link_to firearm.model, firearm %></li>
                <% end %>
            </ul>
        </li>
    </ul>
</div>

app/views/pages/home.html.erb
<h1>Armory</h1>
<p>Welcome to Armory. An inventory management app designed with firearms in mind. </p>

<% if @current_user.present? %>
    <p>Logged in as: <%= @current_user.email %></p>
<% end %>

app/views/session/new.html.erb
<h1>Sign in</h1>

<%= form_tag login_path do %>

    <%= label_tag :email %>
    <%= email_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag "Sign in", :class => 'btn btn-success' %>

<% end %>

<h3>Sample profiles:</h3>
<p>kyle@kiss.fm - chicken (set data)</p>
<p>jackio@kiss.fm - chicken (different set data)</p>
<p>test@empty.com - chicken (no data)</p>

<% if flash[:error].present? %>
    <h2><%= flash[:error] %></h2>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for @user do |f| %>

    <%= f.label :email %>
    <%= f.email_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Sign up", :class => 'btn btn-success' %>

<% end %>

<% if @user.errors.any? %>
    <ol>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ol>
<% end %>